version: '3'
services:
  mqttalk:
    image: mqttalk/dev:latest
    environment:
     - MQTTALK_Client__IceStunUrl=stun:stunturn.mobilegees.com
     - MQTTALK_Client__IceTurnUrl=turn:stunturn.mobilegees.com
     - MQTTALK_Client__IceUsername=mqttalk
     - MQTTALK_Client__IceCredential=mqttalk
    ports:
     - "8080:80"
     