version: '3'
services:
  mssql:
    image: microsoft/mssql-server-linux:latest
    environment:
      SA_PASSWORD: "123qwe!!fooBar"
      ACCEPT_EULA: "Y"
    expose:
     - "1433"
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    image: mqttalk/backend:latest
    environment:
      MQTTALK_Client__IceStunUrl: "stun:stunturn.mobilegees.com"
      MQTTALK_Client__IceTurnUrl: "turn:stunturn.mobilegees.com"
      MQTTALK_Client__IceUsername: "mqttalk"
      MQTTALK_Client__IceCredential: "mqttalk"
      MQTTALK_Server__Jwt__Issuer: "http://localhost/"
      MQTTALK_Server__Jwt__Secret: "fc1d4f60-f18b-4bfc-829b-103e7d2f692c"
      MQTTALK_Server__Jwt__TokenLifeTime: "30"
      MQTTALK_Server__Database__Identity: "Server=mssql,1433;Database=UserDatabase;User ID=SA;Password=123qwe!!fooBar;"
      MQTTALK_Server__Database__Chat: "Server=mssql,1433;Database=ChatDatabase;User ID=SA;Password=123qwe!!fooBar;"
    ports: 
     - "8080:80"
    depends_on:
     - mssql
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    image: mqttalk/client:latest
    ports:
      - 3000:80