POST http://localhost:53456/Account/Register HTTP/1.1
Content-Type: application/json

{
	"Email": "joris.baiutti@gmail.com",
	"Password": "SomeSecurePassword123!"
}

###
POST http://localhost:53457/Account/login HTTP/1.1
Content-Type: application/json

{
	"Email": "joris.baiutti@gmail.com",
	"Password": "SomeSecurePassword123!"
}

###
Get http://localhost:53457/Test/someData
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb3Jpcy5iYWl1dHRpQGdtYWlsLmNvbSIsImp0aSI6ImZmZGVmZmQzLWMzNjctNDBkYi05NWQ3LTQzN2JlOTdlZWFhMCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiYjViNDg3ZTAtYzY2Ny00MzEyLWJjNDQtMzk3OWIzZTQ1MmE3IiwiZXhwIjoxNTQzNTgzNzg4LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0LyIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QvIn0.POgyxMi1Sq1BnVnmfg0FOlv45TNArfmCv8bX-2I8OC4