POST http://localhost:53457/api/Account/Register HTTP/1.1
Content-Type: application/json

{
	"Email": "asfdasdf@gmail.com",
	"Password": "SomeSecurePassword123!"
}

###
POST http://localhost:53457/api/Account/login HTTP/1.1
Content-Type: application/json

{
	"Email": "joris.baiutti@gmail.com",
	"Password": "SomeSecurePassword123!"
}

###
Get http://localhost:53457/Test/someData
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb3Jpcy5iYWl1dHRpQGdtYWlsLmNvbSIsImp0aSI6IjQ4NDQyZTYzLTMxZGUtNDgzMy04ZGUxLTIyNTZjZDdkZWRiYiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiYjViNDg3ZTAtYzY2Ny00MzEyLWJjNDQtMzk3OWIzZTQ1MmE3IiwiZXhwIjoxNTQ0MTE1ODA5LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0LyIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QvIn0.WdznvxNjy1NCnO0LIRNOMgENUrxuM_69tmKDZOW49rc

###
GET http://localhost:8080/api/config HTTP/1.1
Content-Type: application/json

###
GET url HTTP/1.1
Content-Type: application/json

